version: "3.7"
services:
  auth:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
    command:
      - start-dev
      - --import-realm
    ports:
      - "8079:8080"
    expose:
      - 8079
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json